# Generated by Django 5.2.8 on 2025-11-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
