# Generated by Django 5.2.8 on 2025-11-21 12:58

import django.core.validators
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в username', regex='^[\\w.@+-]+\\Z'), reviews.validators.validate_username_not_me]),
        ),
    ]
